const VALIDATION_ERROR_CODE = 400;
const AUTHENTICATION_ERROR_CODE = 401;
const FORBIDDEN_ERROR_CODE = 403;
const NOT_FOUND_ERROR_CODE = 404;
const ASSERTION_ERROR_CODE = 409;
const SERVER_ERROR_CODE = 500;

module.exports = {
  VALIDATION_ERROR_CODE,
  AUTHENTICATION_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  ASSERTION_ERROR_CODE,
  SERVER_ERROR_CODE,
};
